/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Alerts {
  createdAt: Generated<Timestamp>;
  fcmToken: string;
  id: Generated<string>;
  isActive: Generated<boolean>;
  symbol: string;
  targetPrice: Numeric;
  triggeredAt: Timestamp | null;
  updatedAt: Generated<Timestamp>;
  userId: string;
}

export interface SchemaMigrations {
  dirty: boolean;
  version: Int8;
}

export interface DB {
  alerts: Alerts;
  schemaMigrations: SchemaMigrations;
}
